### ISSUE TITLE
Paged buyers

### ISSUE THREAD

**Issue by Maximvdw** [xfrocks/bdPaygates#6]
Problem: When there are a lot of buyers page load times are really slow, and I recently started to get timeouts on my mobile browser sometimes.
With for example 2k users in the buyers this means that 2k avatars are downloaded, etc...
a layout with multiple pages would be nice (showing X per page). Currently my browser sometimes takes 10-15 seconds to load a page

**Comment by daohoangson** [comment]
Good idea :+1: Will try to implement this in the next version.

**Comment by Maximvdw** [comment]
Thanks, maybe some additional info that may be useful:

The only big downside of paged lists are that you can't search. It would be cool if there was like a choice to 1) sort the buyers based on purchase date, userid (like now), alphabetically
2) still allow to show either: "all" ,"100", "25" ,... per page 

Regards,
Maxim

**Comment by daohoangson** [comment]
Fixed via d1763d1

**Comment by drtshock** [comment]
This is awesome. Thank you <3
