### ISSUE TITLE
Rounding of stars

### ISSUE THREAD

**Issue by Maximvdw** [xfrocks/bdPaygates#7]
Dear,

The global rating of an author is already rounded
(http://i.mvdw-software.com/28-12-2015_14-56-35.png)

However is it normal that the rounding of the individual resources isn't? For example: 4.95 still is 4,5 stars (visually).

(Personally I don't mind, but it feels a bit inconsistent)

Best Regards,
Maxim

**Comment by daohoangson** [comment]
This feature is not related to this add-on. It is built into XenForo Resource Manager.
