### ISSUE TITLE
Issue with file-check

### ISSUE THREAD

**Issue by McAtze** [xfrocks/bdPaygates#9]
Hi there,

i get an error with the file-check ..

_library/bdPaygate/ShippableHelper/TempFile.php_

_library/WidgetFramework/ShippableHelper/TempFile.php_

**Comment by daohoangson** [comment]
Looks like an issue with our packager. New release should fix this problem, sorry for the inconvenience.

**Comment by daohoangson** [comment]
Fixed via cd783dd (v1.5.2)
